name: CI
on: [push]
jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setuo-node
        uses: actions/setup-node@v2   # recommended by Github

      - name: Install packages
        run: npm ci
      - name: Run ESlint
        run: npm run lint
      - name: Run Tests
        run: npm run ci:test